/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#dae2fd',
        'on-primary-fixed-variant': '#004e61',
        'outline-variant': '#bdc8ce',
        'primary-container': '#007f9d',
        primary: '#00647c',
        'secondary-container': '#6cf8bb',
        'surface-variant': '#dae2fd',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'surface-tint': '#006780',
        'secondary-fixed-dim': '#4edea3',
        'secondary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#005236',
        'on-primary-container': '#fafdff',
        'primary-fixed': '#b7eaff',
        'inverse-primary': '#6cd3f7',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container': '#eaedff',
        'error-container': '#ffdad6',
        outline: '#6e797e',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#faf8ff',
        'surface-container-high': '#e2e7ff',
        'on-secondary-container': '#00714d',
        'tertiary-fixed-dim': '#ffb2b7',
        'surface-dim': '#d2d9f4',
        'primary-fixed-dim': '#6cd3f7',
        'tertiary-fixed': '#ffdadb',
        error: '#ba1a1a',
        'on-primary-fixed': '#001f28',
        'on-surface': '#131b2e',
        'on-background': '#131b2e',
        'on-surface-variant': '#3e484d',
        tertiary: '#b90538',
        'surface-container-low': '#f2f3ff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed-variant': '#92002a',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#40000d',
        background: '#faf8ff',
        'inverse-surface': '#283044',
        surface: '#faf8ff',
        'on-secondary-fixed': '#002113',
        'tertiary-container': '#dc2c4f',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      spacing: {
        'touch-action': '3.5rem',
        'gutter-desktop': '1.5rem',
        'margin-screen': '1.25rem',
        'stack-tight': '0.5rem',
        'touch-min': '3rem',
        'stack-loose': '1.5rem',
        'stack-base': '1rem',
        'card-padding': '1.25rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'stream-flow': {
          '0%': { backgroundPosition: '0% 50%' },
          '100%': { backgroundPosition: '-200% 50%' },
        },
        'stream-ripple': {
          '0%, 100%': { opacity: '0.28', transform: 'scale(0.96)' },
          '50%': { opacity: '0.72', transform: 'scale(1)' },
        },
      },
      animation: {
        'stream-flow': 'stream-flow 24s linear infinite',
        'stream-ripple': 'stream-ripple 8s ease-in-out infinite',
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        display: [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' },
        ],
        'headline-md': [
          '20px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-lg': [
          '15px',
          { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '700' },
        ],
        'label-sm': [
          '11px',
          { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' },
        ],
        'headline-lg': [
          '30px',
          { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [],
}
